### ISSUE TITLE
Formatting issue

### ISSUE THREAD

**Issue by Ziggy9263** [seanc/bridge#2]
I noticed that if I put angle brackets i.e. < or > in to the discord it doesn't display those brackets in IRC.
For instance, I put the message "kisses > oauth" and in irc it just said "kisses[2xwhitespace]oauth"

It does the same thing with emojis/discord stickers like when someone sends a smiley face or something.

I don't know of any other instances.

**Comment by Fudster** [comment]
Has this been fixed already? 

I can't seem to reproduce this bug.

**Comment by seanc** [comment]
i fixed this already. https://github.com/seanc/bridge/commit/a0222061b22c8314d4f2b3593fa77a4411b1133e
